/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "./rtl/alu.v:1" *)
module alu_4bit(A, B, ALU_Sel, Cin, Y, Cout, Zero);
  (* src = "./rtl/alu.v:22" *)
  wire [4:0] _00_;
  (* src = "./rtl/alu.v:22" *)
  wire [4:0] _01_;
  (* src = "./rtl/alu.v:51" *)
  wire [4:0] _02_;
  (* src = "./rtl/alu.v:31" *)
  wire [3:0] _03_;
  wire _04_;
  (* src = "./rtl/alu.v:46" *)
  wire [3:0] _05_;
  (* src = "./rtl/alu.v:36" *)
  wire [3:0] _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  (* src = "./rtl/alu.v:26" *)
  wire [4:0] _15_;
  (* src = "./rtl/alu.v:56" *)
  wire [4:0] _16_;
  (* src = "./rtl/alu.v:41" *)
  wire [3:0] _17_;
  (* src = "./rtl/alu.v:2" *)
  input [3:0] A;
  (* src = "./rtl/alu.v:4" *)
  input [2:0] ALU_Sel;
  (* src = "./rtl/alu.v:3" *)
  input [3:0] B;
  (* src = "./rtl/alu.v:5" *)
  input Cin;
  (* src = "./rtl/alu.v:8" *)
  output Cout;
  (* src = "./rtl/alu.v:7" *)
  output [3:0] Y;
  (* src = "./rtl/alu.v:9" *)
  output Zero;
  assign _00_ = A + (* src = "./rtl/alu.v:22" *) B;
  assign _01_ = _00_ + (* src = "./rtl/alu.v:22" *) Cin;
  assign _02_ = A + (* src = "./rtl/alu.v:51" *) 4'h1;
  assign _03_ = A & (* src = "./rtl/alu.v:31" *) B;
  assign _04_ = | { _09_, _10_, _11_, _12_ };
  assign Zero = ! (* src = "./rtl/alu.v:62" *) Y;
  assign _05_ = ~ (* src = "./rtl/alu.v:46" *) A;
  assign _06_ = A | (* src = "./rtl/alu.v:36" *) B;
  function [0:0] _26_;
    input [0:0] a;
    input [4:0] b;
    input [4:0] s;
    (* full_case = 32'd1 *)
    (* src = "./rtl/alu.v:54|./rtl/alu.v:19" *)
    (* parallel_case *)
    casez (s)
      5'b????1:
        _26_ = b[0:0];
      5'b???1?:
        _26_ = b[1:1];
      5'b??1??:
        _26_ = b[2:2];
      5'b?1???:
        _26_ = b[3:3];
      5'b1????:
        _26_ = b[4:4];
      default:
        _26_ = a;
    endcase
  endfunction
  assign Cout = _26_(1'hx, { _01_[4], _15_[4], 1'h0, _02_[4], _16_[4] }, { _14_, _13_, _04_, _08_, _07_ });
  function [3:0] _27_;
    input [3:0] a;
    input [31:0] b;
    input [7:0] s;
    (* full_case = 32'd1 *)
    (* src = "./rtl/alu.v:54|./rtl/alu.v:19" *)
    (* parallel_case *)
    casez (s)
      8'b???????1:
        _27_ = b[3:0];
      8'b??????1?:
        _27_ = b[7:4];
      8'b?????1??:
        _27_ = b[11:8];
      8'b????1???:
        _27_ = b[15:12];
      8'b???1????:
        _27_ = b[19:16];
      8'b??1?????:
        _27_ = b[23:20];
      8'b?1??????:
        _27_ = b[27:24];
      8'b1???????:
        _27_ = b[31:28];
      default:
        _27_ = a;
    endcase
  endfunction
  assign Y = _27_(4'hx, { _01_[3:0], _15_[3:0], _03_, _06_, _17_, _05_, _02_[3:0], _16_[3:0] }, { _14_, _13_, _12_, _11_, _10_, _09_, _08_, _07_ });
  assign _07_ = ALU_Sel == (* full_case = 32'd1 *) (* src = "./rtl/alu.v:54|./rtl/alu.v:19" *) 3'h7;
  assign _08_ = ALU_Sel == (* full_case = 32'd1 *) (* src = "./rtl/alu.v:49|./rtl/alu.v:19" *) 3'h6;
  assign _09_ = ALU_Sel == (* full_case = 32'd1 *) (* src = "./rtl/alu.v:44|./rtl/alu.v:19" *) 3'h5;
  assign _10_ = ALU_Sel == (* full_case = 32'd1 *) (* src = "./rtl/alu.v:39|./rtl/alu.v:19" *) 3'h4;
  assign _11_ = ALU_Sel == (* full_case = 32'd1 *) (* src = "./rtl/alu.v:34|./rtl/alu.v:19" *) 3'h3;
  assign _12_ = ALU_Sel == (* full_case = 32'd1 *) (* src = "./rtl/alu.v:29|./rtl/alu.v:19" *) 3'h2;
  assign _13_ = ALU_Sel == (* full_case = 32'd1 *) (* src = "./rtl/alu.v:25|./rtl/alu.v:19" *) 3'h1;
  assign _14_ = ! (* full_case = 32'd1 *) (* src = "./rtl/alu.v:21|./rtl/alu.v:19" *) ALU_Sel;
  assign _15_ = A - (* src = "./rtl/alu.v:26" *) B;
  assign _16_ = A - (* src = "./rtl/alu.v:56" *) 4'h1;
  assign _17_ = A ^ (* src = "./rtl/alu.v:41" *) B;
endmodule
